stages:
  - test

variables:
  ANSIBLE_FORCE_COLOR: 'true'

before_script:
  - apk add --no-cache ansible || true
  - yum install -y ansible || true
  - sh -c "apt-get update && apt-get install -y python3-pip && pip3 install ansible" || true

test-fedora-29:
  stage: test
  image: fedora:29
  script: &test
    - ansible-playbook tests/test.yml
    - ansible-playbook tests/test.yml

test-fedora-28:
  stage: test
  image: fedora:28
  script: *test

test-centos-7:
  stage: test
  image: centos:7
  script: *test

test-ubuntu-bionic:
  stage: test
  image: ubuntu:bionic
  script: *test

test-debian-stretch:
  stage: test
  image: debian:stretch
  script: *test

test-alpine-3.8:
  stage: test
  image: alpine:3.8
  script: *test
